"""Verified Data Science Lab script-registration operations used by pipelines."""

from __future__ import annotations

import base64
import json
import random
from typing import Any

from .client import BDBClient


def random_cell_id() -> str:
    """Return the cell identifier shape generated by the BDB editor."""
    return f"0_{random.random()}"


def make_rich_cell(source: str, cell_id: str | None = None) -> dict[str, Any]:
    """Build the editor-state cell persisted while creating/saving a notebook."""
    return {
        "id": cell_id or random_cell_id(),
        "pre_cell_id": 0,
        "type": "code",
        "is_pre_cell": False,
        "succORerr": False,
        "code": source,
        "count": 0,
        "mode": "preview",
        "result": "",
        "outputArray": [],
        "image": "",
        "error": "",
        "hover": True,
        "interrupt": False,
        "warning": False,
        "lineNumber": False,
        "laodmodel": False,
        "expand": False,
        "outputexpand": False,
        "readonly": False,
        "loader": False,
        "markDowns": False,
        "cellType": "code",
        "algorithms": "",
        "semicolon": "",
        "cputimes": "",
        "showcputime": False,
        "secret": [],
        "kpiData": [],
        "updatedViewDef": None,
        "showRecordsEditDrawer": False,
        "recordsEditDrawerData": None,
        "widget": None,
    }


def make_simple_cell(source: str, cell_id: str | None = None) -> dict[str, Any]:
    """Build the compact cell stored in a registered pipeline script."""
    return {
        "id": cell_id or random_cell_id(),
        "code": source,
        "count": 0,
        "error": "",
        "type": "code",
        "ischecked": True,
    }


def build_editor_state(source: str) -> dict[str, Any]:
    return {
        "datasets": [],
        "uncheckeddatasets": [],
        "code": [make_rich_cell(source)],
        "kernalID": "",
        "Algorithms": [],
        "isScheduled": 0,
        "last_modified_date": "",
    }


def build_register_payload(
    source: str, external_libraries: list[Any] | None = None
) -> dict[str, str]:
    return {
        "DSLAB_content": json.dumps([make_simple_cell(source)]),
        "pipeline_content": json.dumps(source),
        "externalLibraries": json.dumps(external_libraries or []),
    }


def extract_notebook_id(response: Any) -> str | None:
    if not isinstance(response, dict):
        return None
    notebook = response.get("notebook")
    if isinstance(notebook, str):
        try:
            notebook = json.loads(notebook)
        except (TypeError, ValueError):
            notebook = None
    if isinstance(notebook, dict) and notebook.get("id") is not None:
        return str(notebook["id"])
    data = response.get("data")
    candidates = [
        response.get("id"),
        response.get("notebookId"),
        data.get("id") if isinstance(data, dict) else None,
        data.get("notebookId") if isinstance(data, dict) else None,
    ]
    return next((str(item) for item in candidates if item is not None), None)


class DSLabService:
    """Minimal DS Lab notebook/script client required by pipeline automation."""

    CONSUMER = "NOTEBOOK"

    def __init__(self, client: BDBClient) -> None:
        self.client = client

    def _save_notebook(
        self,
        token: str,
        payload: dict[str, Any],
        *,
        docid: str,
        user_id: str,
    ) -> dict[str, Any]:
        encoded = base64.b64encode(
            json.dumps(payload).encode("utf-8")
        ).decode("ascii")
        response = self.client.post(
            "/cxf/bizviz/pluginService",
            {
                "serviceName": "saveNotebook",
                "consumerName": self.CONSUMER,
                "spacekey": self.client.config.spacekey,
                "loggedUser": user_id,
                "data": encoded,
            },
            {
                "authtoken": token,
                "spacekey": self.client.config.spacekey,
                "userID": user_id,
                "docid": docid,
            },
        )
        if not isinstance(response, dict):
            raise RuntimeError("saveNotebook returned a non-object response")
        if response.get("success") is False:
            message = response.get("message") or "saveNotebook was not successful"
            raise RuntimeError(str(message))
        return response

    def register_python_script(
        self,
        token: str,
        *,
        project_id: str,
        notebook_name: str,
        source: str,
        external_libraries: list[Any] | None = None,
        user_id: str = "",
    ) -> dict[str, Any]:
        """Create, save, and register one existing-project Python script."""
        if not str(project_id).strip():
            raise ValueError("project_id must be a non-empty value")
        if not str(notebook_name).strip():
            raise ValueError("notebook_name must be a non-empty value")
        if not isinstance(source, str) or not source.strip():
            raise ValueError("source must be non-empty Python source")

        create_response = self._save_notebook(
            token,
            {
                "notebook": notebook_name,
                "projectId": str(project_id),
                "isImported": 0,
                "data": json.dumps(build_editor_state(source)),
            },
            docid="0",
            user_id=user_id,
        )
        notebook_id = extract_notebook_id(create_response)
        if not notebook_id:
            raise RuntimeError(
                "register_python_script could not resolve notebookId"
            )

        docid = f"{project_id}_{notebook_id}"
        self._save_notebook(
            token,
            {
                "notebook": notebook_name,
                "projectId": str(project_id),
                "isImported": 0,
                "data": json.dumps(build_editor_state(source)),
                "id": notebook_id,
            },
            docid=docid,
            user_id=user_id,
        )
        self._save_notebook(
            token,
            {
                "id": notebook_id,
                "customComponentscript": json.dumps(
                    build_register_payload(source, external_libraries)
                ),
                "isScheduled": 0,
            },
            docid=docid,
            user_id=user_id,
        )
        return {"notebookId": notebook_id, "createResponse": create_response}
